services:
  - type: web
    name: controle-medicamento-site
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db-medicamentos-bootcamp
          property: connectionString

databases:
  
  - name: db-medicamentos-bootcamp
    plan: free
    databaseName: controle_medicamentos
    user: admin