name: CI - PHP

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Verificar sintaxe (Lint)
        run: |
          php -l index.php
          php -l login.php
          php -l logout.php
          php -l src/conexao.php
          php -l src/inserir.php
          php -l src/editar.php
          php -l src/excluir.php

      - name: Rodar testes
        run: php tests/testes.php